server:
  port: 6060

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: full
          poke-api:
            url: https://pokeapi.co/api/v2
